package lk.wholesaledist.view;


import lk.wholesaledist.view.ViewItemForm;
import lk.wholesaledist.controller.ItemController;
import lk.wholesaledist.model.ItemModel;
import lk.wholesaledist.model.MovbleModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author danu
 */
public class SystemReportForm extends javax.swing.JFrame {

    /**
     * Creates new form SystemReportForm
     */
    public SystemReportForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        mostMovbleBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        leatMovbleBtn = new javax.swing.JButton();
        incomeBtn = new javax.swing.JButton();
        customerIncomeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ItemTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        ItemTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(236, 240, 241));
        jPanel1.setPreferredSize(new java.awt.Dimension(561, 449));

        jPanel2.setBackground(new java.awt.Color(26, 188, 156));

        jLabel4.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(213, 0, 0));
        jLabel4.setText("SYSTEM REPORTS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        mostMovbleBtn.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        mostMovbleBtn.setForeground(new java.awt.Color(62, 39, 35));
        mostMovbleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/wholesaledist/pic/most.png"))); // NOI18N
        mostMovbleBtn.setText("Most Movble Item");
        mostMovbleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostMovbleBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(62, 39, 35));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/wholesaledist/pic/BackButton.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        leatMovbleBtn.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        leatMovbleBtn.setForeground(new java.awt.Color(62, 39, 35));
        leatMovbleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/wholesaledist/pic/dowj.png"))); // NOI18N
        leatMovbleBtn.setText("Least Movble Item");
        leatMovbleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leatMovbleBtnActionPerformed(evt);
            }
        });

        incomeBtn.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        incomeBtn.setForeground(new java.awt.Color(62, 39, 35));
        incomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/wholesaledist/pic/annual Income.png"))); // NOI18N
        incomeBtn.setText("Daily/ Monthly/ Annual Income");
        incomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeBtnActionPerformed(evt);
            }
        });

        customerIncomeBtn.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        customerIncomeBtn.setForeground(new java.awt.Color(62, 39, 35));
        customerIncomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/wholesaledist/pic/customerIncome.png"))); // NOI18N
        customerIncomeBtn.setText("Customer Wise Income");
        customerIncomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIncomeBtnActionPerformed(evt);
            }
        });

        ItemTable.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        ItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Description", "Pack Size"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ItemTable.setRowHeight(29);
        jScrollPane1.setViewportView(ItemTable);

        ItemTable2.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        ItemTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Description", "Pack Size"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ItemTable2.setRowHeight(28);
        jScrollPane3.setViewportView(ItemTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(customerIncomeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mostMovbleBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(incomeBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(leatMovbleBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostMovbleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(leatMovbleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(incomeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(customerIncomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostMovbleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostMovbleBtnActionPerformed
        try {
            ArrayList<MovbleModel> itemList= ItemController.getMostMobleItem();
            DefaultTableModel dtm = (DefaultTableModel) ItemTable.getModel();
            dtm.setRowCount(0);
            for (MovbleModel item : itemList) {
              //  Object[] rowData={item.getCode(),item.getDiscription(),item.getUnitPrice(),item.getQtyOnHand()};
               // dtm.addRow(rowData);
               String itemCode = item.getItemCode();
               
               try {
                    ItemModel itemFull = ItemController.searchMostMovbleItem(itemCode);
                     if(itemFull != null){
                            Object[] rowData={itemFull.getItemCode(),itemFull.getDescription(),itemFull.getPackSize()};
                            dtm.addRow(rowData);
                        }else{
                            JOptionPane.showMessageDialog(this, "Item not found...");
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage());
                    } catch (ClassNotFoundException ex) {
                            JOptionPane.showMessageDialog(this, "Driver not found...");
                    }
            }

        } catch (SQLException ex) {
            Logger.getLogger(ViewItemForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver not found...");
        }
        
    }//GEN-LAST:event_mostMovbleBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        dispose();
        new AdministorForm().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void leatMovbleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leatMovbleBtnActionPerformed
        try {
            ArrayList<MovbleModel> itemList= ItemController.getLeavbleItem();
            DefaultTableModel dtm = (DefaultTableModel) ItemTable2.getModel();
            dtm.setRowCount(0);
            for (MovbleModel item : itemList) {
              //  Object[] rowData={item.getCode(),item.getDiscription(),item.getUnitPrice(),item.getQtyOnHand()};
               // dtm.addRow(rowData);
               String itemCode = item.getItemCode();
               
               try {
                    ItemModel itemFull = ItemController.searchLeavbleItem(itemCode);
                     if(itemFull != null){
                            Object[] rowData={itemFull.getItemCode(),itemFull.getDescription(),itemFull.getPackSize()};
                            dtm.addRow(rowData);
                        }else{
                            JOptionPane.showMessageDialog(this, "Item not found...");
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage());
                    } catch (ClassNotFoundException ex) {
                            JOptionPane.showMessageDialog(this, "Driver not found...");
                    }
            }

        } catch (SQLException ex) {
            Logger.getLogger(ViewItemForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver not found...");
        }
        
    }//GEN-LAST:event_leatMovbleBtnActionPerformed

    private void incomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incomeBtnActionPerformed

    private void customerIncomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIncomeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIncomeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemReportForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ItemTable;
    private javax.swing.JTable ItemTable2;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton customerIncomeBtn;
    private javax.swing.JButton incomeBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton leatMovbleBtn;
    private javax.swing.JButton mostMovbleBtn;
    // End of variables declaration//GEN-END:variables
}
